# Generated by Django 2.2.1 on 2019-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('period', models.DateField()),
            ],
        ),
    ]
